services:
  
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    build:
      context: .
    # image: fagnerpimentel/aprendendo_ros2:latest
    ipc: host
    volumes:
      - ./src:/home/robot/ws_aprendendo_ros2/src:rw
    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
      - LDS_MODEL=LDS-02
      - TURTLEBOT3_MODEL=burger
    ports:
      - "3001:80"
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     code serve-web --host 0.0.0.0 --port 80 --without-connection-token --accept-server-license-terms